In [5]:
import numpy as np

np.empty([2, 2], int)


array([[0, 0],
       [0, 0]])

In [7]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty_like(X)


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.ones((3, 2), float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

In [17]:
np.zeros((3,2), float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

In [26]:
np.ones((2,5), dtype = np.int64)*6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=int64)

In [27]:
np.full((2, 5), 6, dtype=np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [28]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)

In [29]:
np.array([1, 2, 3])

array([1, 2, 3])

In [30]:
x = [1,2]
np.array(x)

array([1, 2])

In [31]:
X = np.array([[1, 2], [3, 4]])


In [32]:
X


array([[1, 2],
       [3, 4]])

In [33]:
np.matrix(X)

matrix([[1, 2],
        [3, 4]])

In [34]:
x = [1, 2]
np.array(x, float)

array([1., 2.])

In [43]:
x = np.array([30])
np.asscalar(x)

<ipython-input-43-70018d9ba490>:2: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  np.asscalar(x)


30

In [51]:
x = np.array([1, 2, 3])
y = x
print(id(x))
print(id(y))

2004951285392
2004951285392


In [53]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [59]:
np.logspace(3, 10, 50, endpoint = False)

array([1.00000000e+03, 1.38038426e+03, 1.90546072e+03, 2.63026799e+03,
       3.63078055e+03, 5.01187234e+03, 6.91830971e+03, 9.54992586e+03,
       1.31825674e+04, 1.81970086e+04, 2.51188643e+04, 3.46736850e+04,
       4.78630092e+04, 6.60693448e+04, 9.12010839e+04, 1.25892541e+05,
       1.73780083e+05, 2.39883292e+05, 3.31131121e+05, 4.57088190e+05,
       6.30957344e+05, 8.70963590e+05, 1.20226443e+06, 1.65958691e+06,
       2.29086765e+06, 3.16227766e+06, 4.36515832e+06, 6.02559586e+06,
       8.31763771e+06, 1.14815362e+07, 1.58489319e+07, 2.18776162e+07,
       3.01995172e+07, 4.16869383e+07, 5.75439937e+07, 7.94328235e+07,
       1.09647820e+08, 1.51356125e+08, 2.08929613e+08, 2.88403150e+08,
       3.98107171e+08, 5.49540874e+08, 7.58577575e+08, 1.04712855e+09,
       1.44543977e+09, 1.99526231e+09, 2.75422870e+09, 3.80189396e+09,
       5.24807460e+09, 7.24435960e+09])

In [60]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

In [70]:
x = np.arange(1,5)
np.diag(np.diag(x))

array([1, 2, 3, 4])

In [71]:
np.diagflat([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [72]:
x = np.array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])
x.shape

(3, 5)

In [73]:
x.size

15

In [75]:
x.reshape(3,5)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [76]:
x = np.array([[ 0, 0, 0], [ 4, 0, 0], [ 7, 8, 0], [10, 11, 12]])
np.tril(x)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [83]:
np.triu(np.arange(1, 13).reshape(4, 3), k = -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])